### PR TITLE
Allow passing additional arguments to the `make_cte_queryset` function

### PR DESCRIPTION
**Pull request by nobabar**
Add `*args` and `**kwargs`arguments to the `With.recursive` method that will then be passed to the `make_cte_queryset` function.

This will allow further customization of the `make_cte_queryset` function, e.g. by passing `request.user` to it to filter by user directly in SQL or for any kind of dynamic filter.

### CODE REVIEW

**Comment by millerdev** [comment]
I don't think this is necessary, and it limits future changes that can made to the`With.recursive()` interface. For example, if it became necessary to add another argument to `With.recursive()`, it would not be possible to do so without potentially breaking existing code that since the new argument might conflict with arguments intended for `make_cte_queryset`.

A closure can be used to access external "arguments" to `make_cte_queryset`. For example:

```py
extra_arg = ...

def make_cte(cte):
    # extra_arg can be referenced here
    ...

cte = With.recursive(make_cte)
```

**Comment by nobabar** [comment]
The idea was to pass query or path parameters from a view to the cte so, unless I missed something else, global variables don't seem to address this problem.

**Comment by millerdev** [comment]
A closure doesn't need to use global variables. For example:
```py
def build_cte_for(user):
    def make(cte):
        # user can be referenced here
        ...

    return With.recursive(make)


user_cte = build_cte_for(user)
```

**Comment by millerdev** [comment]
@nobabar it appears you may have published [this project on test.pypi.org](https://test.pypi.org/project/django-cte/). Would you be willing to transfer ownership to "dimagi" so we can do publication testing, please?

To do that you would go to https://test.pypi.org/manage/project/django-cte/collaboration/
- Enter "dimagi" in the User field
- Select a role such as Owner. We are requesting to be the owner since we own the [package on pypi](https://pypi.org/project/django-cte/).
- Click Invite.

Thank you.

**Comment by nobabar** [comment]
that's done

**Pull request closed without merging**
