### PR TITLE
Fix OuterRef resolution in CTE subquery

### PR DESCRIPTION
**Pull request by SebCorbin**

### CODE REVIEW

**Comment by SebCorbin** [comment]
@millerdev Hey, I tackled this problem by implementing a CTESubquery class that also resolve expressions in `_with_cte`

**Comment by millerdev** [comment]
Thanks for your contribution @SebCorbin. I will try to find some time to review it soon.

**Comment by millerdev** [comment]
@SebCorbin I would prefer not to add another public `CTE*` class if possible. I found a way to get around that in #19. However, the effort you put into this was very helpful. Thank you!

**Comment by SebCorbin** [comment]
Nice, that’s an even better solution!

**Pull request closed without merging**
